"""
Murph - LLM Prompts
Prompt templates for LLM integration.
"""

from .consolidation_prompts import (
    CONTEXT_SUMMARY_SYSTEM_PROMPT,
    CONTEXT_SUMMARY_USER_PROMPT,
    EVENT_SUMMARY_SYSTEM_PROMPT,
    EVENT_SUMMARY_USER_PROMPT,
    EXPERIENCE_REFLECTION_SYSTEM_PROMPT,
    EXPERIENCE_REFLECTION_USER_PROMPT,
    RELATIONSHIP_NARRATIVE_SYSTEM_PROMPT,
    RELATIONSHIP_NARRATIVE_USER_PROMPT,
)
from .reasoning_prompts import (
    BEHAVIOR_REASONING_SYSTEM_PROMPT,
    BEHAVIOR_REASONING_USER_PROMPT,
)
from .vision_prompts import (
    SCENE_ANALYSIS_SYSTEM_PROMPT,
    SCENE_ANALYSIS_USER_PROMPT,
    VALID_LLM_TRIGGERS,
)

__all__ = [
    "SCENE_ANALYSIS_SYSTEM_PROMPT",
    "SCENE_ANALYSIS_USER_PROMPT",
    "VALID_LLM_TRIGGERS",
    "BEHAVIOR_REASONING_SYSTEM_PROMPT",
    "BEHAVIOR_REASONING_USER_PROMPT",
    "EVENT_SUMMARY_SYSTEM_PROMPT",
    "EVENT_SUMMARY_USER_PROMPT",
    "RELATIONSHIP_NARRATIVE_SYSTEM_PROMPT",
    "RELATIONSHIP_NARRATIVE_USER_PROMPT",
    "EXPERIENCE_REFLECTION_SYSTEM_PROMPT",
    "EXPERIENCE_REFLECTION_USER_PROMPT",
    "CONTEXT_SUMMARY_SYSTEM_PROMPT",
    "CONTEXT_SUMMARY_USER_PROMPT",
]
